apiVersion: v1
kind: Service
metadata:
  name: data-service
spec:
  type: ClusterIP
  selector:
    run: data-server
  ports:
    - port: 8081
      targetPort: 80 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-server
spec:
  selector:
    matchLabels:
      run: data-server
  replicas: 1
  template:
    metadata:
      labels:
        run: data-server
    spec:
      containers:
        - name: data-server
          image: index.docker.io/gaba5/webserver
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: patrickkeyregistry
